### ISSUE TITLE
Focused node state doesn't change with data

### ISSUE THREAD

**Issue by mj1856** [bvaughn/react-flame-graph#9]
I notice that when I change the data passed in through the `data` prop, that the `focusedNode` state still has the information from the focused node of the previous data.

Visually, say I load one flame graph, click the 3rd node down and then load a different flame graph, the 3rd node of the new one is showing, rather than the root node.

**Comment by bvaughn** [comment]
Can you provide a repro? (either Code Sandbox or failing unit test)

**Comment by mj1856** [comment]
I haven't forgot about this, just tied up with other things at the moment.  I'll get back to you when I can.  Thanks.
